from aiogram.types import InlineKeyboardMarkup,InlineKeyboardButton

menu = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='🗯️Меню🗯️',callback_data='menu')
menu.insert(btn1)

menu2 = InlineKeyboardMarkup(row_width=2)
btn1 = InlineKeyboardButton(text='🕕Режим работы🕕',callback_data='rezhim')
btn2 = InlineKeyboardButton(text='🏩Адрес🏩',callback_data='adres')
btn3 = InlineKeyboardButton(text='☎Контактные данные☎',callback_data='contact')
btn4 = InlineKeyboardButton(text='🤩Товар в наличии🤩',callback_data='tovar')
btn6 = InlineKeyboardButton(text='📩Подписка на рассылку📩',callback_data='podpis')
btn7 = InlineKeyboardButton(text='❌Отменить подписку на рассылку❌',callback_data='otpodpis')
btn8 = InlineKeyboardButton(text='🛒Моя корзина🛒',callback_data='korzina')
menu2.insert(btn1)
menu2.insert(btn2)
menu2.insert(btn3)
menu2.insert(btn4)
menu2.insert(btn6)
menu2.insert(btn7)
menu2.insert(btn8)


back = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='↩Вернуться назад в меню↩',callback_data='menu')
back.insert(btn1)

kategorii = InlineKeyboardMarkup(row_width=2)
btn1 = InlineKeyboardButton(text='Рубашки',callback_data='rub')
btn2 = InlineKeyboardButton(text='Футболки',callback_data='fut')
btn3 = InlineKeyboardButton(text='Джинсы',callback_data='dji')
btn4 = InlineKeyboardButton(text='Худи',callback_data='hud')
btn6 = InlineKeyboardButton(text='Куртки',callback_data='kur')
btn7 = InlineKeyboardButton(text='↩Вернуться назад в меню↩',callback_data='menu')
kategorii.insert(btn1)
kategorii.insert(btn2)
kategorii.insert(btn3)
kategorii.insert(btn4)
kategorii.insert(btn6)
kategorii.insert(btn7)

back_k = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='Добавить в корзину',callback_data='add')
btn2 = InlineKeyboardButton(text='↩Вернуться назад в меню↩',callback_data='menu')
back_k.insert(btn1)
back_k.insert(btn2)

back_k2 = InlineKeyboardMarkup(row_width=1)
btn1 = InlineKeyboardButton(text='Очистить корзину',callback_data='clear')
btn2 = InlineKeyboardButton(text='↩Вернуться назад в меню↩',callback_data='menu')
back_k2.insert(btn1)
back_k2.insert(btn2)